apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodie
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

          volumeMounts:
            - name: specialofday
              mountPath: "/food"
            - name: reviewpvc
              mountPath: "/newvol"

      volumes:
        - name: specialofday
          secret:
            secretName: specialofday
        - name: reviewpvc
          persistentVolumeClaim:
            claimName: reviewpvc
