apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reviewpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Mi
  volumeName: reviewvol
