apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviewvol
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 35.158.106.36
    path: "/"
  mountOptions:
    - nfsvers=4.2
