apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-10T12:50:54Z"
  generation: 2
  labels:
    app: try1
  name: try1
  namespace: default
  resourceVersion: "7150"
  uid: 496b04f4-cab6-4892-ad05-a243eee57595
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try1
    spec:
      containers:
        - image: 10.109.24.23:5000/simpleapp
          imagePullPolicy: Always
          name: simpleapp
          readinessProbe:
            periodSeconds: 5
            exec:
              command:
                - cat
                - /tmp/healthy
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: goproxy
          image: k8s.gcr.io/goproxy:0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 6
  conditions:
    - lastTransitionTime: "2022-02-10T12:51:19Z"
      lastUpdateTime: "2022-02-10T12:51:19Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-02-10T12:50:55Z"
      lastUpdateTime: "2022-02-10T12:51:19Z"
      message: ReplicaSet "try1-59c767f658" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
