apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleepy
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: resting
              image: busybox
              command: ["/bin/sleep"]
              args: ["3"]
          restartPolicy: Never
          activeDeadlineSeconds: 10
  schedule: "*/2 * * * *"
